# Cocoapods default sources
source 'https://github.com/CocoaPods/Specs.git'
source 'https://delivery-platform.broadpeak.tv/ios/broadpeak/specs.git'

platform :ios, '10.0'

target 'playkit-ios-broadpeak_Example' do
  use_frameworks!

  pod 'PlayKitBroadpeak', :path => '../'

  pod 'KalturaPlayer/OTT', '~> 4.0'
  #pod 'KalturaPlayer/OTT', :path => '../../kaltura-player-ios'

  target 'playkit-ios-broadpeak_Tests' do
    inherit! :search_paths

  end
end
