# Cocoapods default sources
source 'https://github.com/CocoaPods/Specs.git'
source 'https://delivery-platform.broadpeak.tv/ios/broadpeak/specs.git'

platform :tvos, '11.0'

target 'playkit-tvos-broadpeak' do
  use_frameworks!

  pod 'PlayKitBroadpeak', :path => '../'

  pod 'KalturaPlayer/OTT', '~> 4.0'
  #pod 'KalturaPlayer/OTT', :path => '../../kaltura-player-ios'

  pod 'PlayKit', '~> 3.20'
  #pod 'PlayKit', :path => '../../playkit-ios'

end

# Needed from Xcode 14, supports from tvOS 11, need to updated pods with lower supported value.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end

